version: "2"
services:
  cloudadapter:
    image: anyviz/cloudadapter
    restart: always
    container_name: anyviz
    ports:
      - "8888:8888"
    volumes:
      - anyviz_config:/etc/anyviz
    # required if AnyViz VPN is needed
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
volumes:
  anyviz_config: