version: "2"

services:
  wm-node-red:
    image: wmucdev.azurecr.io/wm-node-red:1.1.2-1.0-alpha.1 
    container_name: uc_addon_node_red 
    network_mode: "host"
    volumes:
      - uc_addon_node_red:/data
    environment: 
      PORT: ${PORT}

volumes:
  uc_addon_node_red: