version: "2"

services:
  uc-addon-procon-web-es:
    image: wmucdev.azurecr.io/uc-addon-procon-web-es:6.4.5-rc.2
    container_name: uc_addon_procon_web_es
    restart: unless-stopped
    volumes:
      - uc_addon_procon_web_es:/root
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "5"
    environment:
      - driver_u_control_web_ipAddress=127.0.0.1
      - grpc_connector_grpcEndpoint=127.0.0.1:7319